### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by TheAmityD**
Just some improvements that I made for your website.
- Added separate CSS files
- Fixed the fonts with the ones from Google Fonts
- Other stuff I can't remember

### CODE REVIEW

**Comment by TheAmityD** [comment]
Also,
- Added 404 page, that I hope will work

**Comment by Coral-Reefs** [comment]
Huh what when did I ever create this-

**Comment by TheAmityD** [comment]
Haha, I'm just making this PR for fun anyways

**Comment by Coral-Reefs** [comment]
You never saw any of this 😭

**Comment by TheAmityD** [comment]
Oop.

**Pull request merged**
